services:
  # Serviço da Base de Dados
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      # Garante a persistência dos dados (Aula 10)
      - mongo_data:/data/db

  # Serviço do Backend FastAPI
  backend:
    build: .
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    depends_on:
      # O backend só arranca depois da DB estar pronta
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/

volumes:
  # Volume nomeado para não perder os votos/users
  mongo_data: