services:
  mongodb:
    image: mongo:7
    container_name: sve_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: sve_backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - MONGO_DB=sve
      - JWT_SECRET=troca_isto_por_uma_chave_grande

volumes:
  mongo_data: